
language: en
useGitignore: true
ignorePaths: 
  - "**/node_modules/**"
  - "**/*.spec.js"
  - "**/buildfiles/**"
  - "**/docs/doc.js"
  - "**/docs/*.css"
  - "**/dropdown-i18n.js"
  - "**/package.json"
words:
  - hrefs # hyperlinks
  - linc # lint changed files only
  - selectbox
  - datafetch
  - templater

dictionaries:
  - "softwareTerms"
  - "misc"
  - "en-gb"
  - "css"
  - "html"
  - "js"
  - "lorem-ipsum"